### ISSUE TITLE
vetted models checklist

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#383]
- [ ] Create a list of unit tests that need to be completed for every model type that is listed in the vetted models help file.
- [ ] Add that list to the vetted models help file
- [ ] Update the unit tests to ensure each model type meets vetted models requirement

**Comment by margarethannum** [comment]
- [ ] Check labels

- [ ] Check that numbers in model match the table_body of tbl_regression object

- [ ] Check Exponentiating works

- [ ] Add_event_n and check that it works appropriately

- [ ] Add_n returns appropriate number for model

- [ ] Model works with tbl_regression and tbl_uvregression

**Comment by margarethannum** [comment]
@jflynn264 and I will tackle this for the hackathon.

**Comment by ddsjoberg** [comment]
A basic infrastructure is set up to vetted new models, and many scenarios are tested now across all vetted model (big improvement wrt standardization, and unit test coverage).  But this should be re-visited at some point to ensure we're doing this to the highest standard.
